ICONOS_CONTENIDO = {
  'saludo': '👋',
  'feliz': '😊',
  'computador': '💻',
  'programador': '👨‍💻',
  'empresa': '🏢',
  'tecnologia': '🛠️',
  'proyecto': '🚀',
  'logro': '🏆',
  'habilidad': '💪',
  'educacion': '🎓',
  'hobby': '🎯',
  'industria': '🏭',
  'tiempo': '⏰',
  'nivel': '📊',
  'liderazgo': '👨‍💼',
  'comunicacion': '🗣️',
  'adaptabilidad': '🔄',
  'resolucion': '🎯',
  'gestion_tiempo': '⏱️',
  'categoria': '📁',
  'arquitectura': '🏗️',
  'documentacion': '📄',
  'aprendizaje': '📚',
  'metricas': '📈',
  'calendario': '📅',
  'experiencia': '💼'
}